plugins {
    id 'com.android.application' version '8.3.0'
}


android {
    compileSdk 34
    namespace "com.knightlight.game"

    defaultConfig {
        applicationId 'com.knightlight.game'
        minSdk 29
        targetSdk 34
        versionCode 1
        versionName '0.0.0'
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }
    }

    signingConfigs {
    }

    buildTypes {
        release {
            // signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            debuggable false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    sourceSets {
        main {
            java.srcDirs = ['src']
            res.srcDirs = ['src/main/res']
            assets.srcDirs = ['assets']
        }
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: 'lib', include: '*.jar')
    implementation('androidx.appcompat:appcompat:1.7.0') {
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
    }
    implementation 'androidx.core:core:1.13.1'
}
