#!/bin/bash
set -euo pipefail
umask 0077

# =====================================================================
#  KnightLight Java-to-HTML Converter v4.0 (LEAN)
#  - Combined single-page source view ONLY
#  - No individual file generation (saves storage)
#  - Audit logging
#  - Manual deployment reminders
# =====================================================================

JAVA_SRC_DIR="src/main/java/com/knightlight/game"
DOCS_DIR="./docs"
LOG_FILE=".conversion-audit.log"

mkdir -p "$DOCS_DIR"
chmod 755 "$DOCS_DIR" 2>/dev/null || true

# ---------------------------------------------------------------------
# Generate ALL_SOURCE.html - combined single-page view (for AI review)
# ---------------------------------------------------------------------
generate_combined_page() {
    local combined_file="${DOCS_DIR}/ALL_SOURCE.html"
    local output="$combined_file"
    local total_files=0
    local total_lines=0
    local nav_html=""

    echo "[INFO] Generating combined source view..."

    # First pass: build nav links and count stats
    for java_file in "$JAVA_SRC_DIR"/*.java; do
        local filename
        filename=$(basename "$java_file" .java)
        local class_id
        class_id=$(echo "${filename,,}" | tr -cd '[:alnum:]')
        local line_count
        line_count=$(wc -l < "$java_file")
        total_files=$((total_files + 1))
        total_lines=$((total_lines + line_count))
        nav_html="${nav_html}<a href=\"#${class_id}\">${filename}</a> "
    done

    # Write header with nav inlined
    cat > "$output" << HEADER
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>KnightLight - All Source</title>
<style>
body { font-family: monospace; background: #1a1a2e; color: #eaeaea; margin: 0; }
header { background: #6d4aff; padding: 20px; position: sticky; top: 0; z-index: 100; }
header h1 { color: white; margin: 0; }
.stats { color: #ccc; font-size: 0.85em; margin-top: 5px; }
nav { background: #2a2a4a; padding: 12px; position: sticky; top: 65px; z-index: 99; overflow-x: auto; white-space: nowrap; }
nav a { color: #aaaaff; text-decoration: none; margin-right: 15px; padding: 4px 8px; border-radius: 4px; }
nav a:hover { background: #4a4a8a; }
.file { border: 1px solid #4a4a8a; margin: 20px; background: #1e1e3e; border-radius: 8px; overflow: hidden; }
.file-header { background: #2a2a5a; padding: 12px 18px; border-bottom: 2px solid #6d4aff; display: flex; justify-content: space-between; align-items: center; }
.file-header h2 { color: #d0d0ff; font-size: 1.2em; margin: 0; }
.file-meta { color: #888; font-size: 0.8em; }
pre { padding: 18px; overflow-x: auto; background: #0f0f1e; margin: 0; white-space: pre; }
code { font-family: "Courier New", monospace; color: #d0d0ff; font-size: 0.9em; }
footer { padding: 25px; color: #666; text-align: center; border-top: 1px solid #4a4a8a; }
</style>
</head>
<body>
<header>
<h1>KnightLight - Complete Source Code</h1>
<div class="stats">${total_files} files | ${total_lines} lines | $(date '+%Y-%m-%d %H:%M')</div>
</header>
<nav>${nav_html}</nav>
<div id="files">
HEADER

    # Second pass: write each file section
    for java_file in "$JAVA_SRC_DIR"/*.java; do
        local filename
        filename=$(basename "$java_file" .java)
        local class_id
        class_id=$(echo "${filename,,}" | tr -cd '[:alnum:]')
        local line_count
        line_count=$(wc -l < "$java_file")
        local file_size
        file_size=$(wc -c < "$java_file")

        local escaped
        escaped=$(sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g' "$java_file")

        cat >> "$output" << FILEBLOCK

<div class="file" id="${class_id}">
    <div class="file-header"><h2>${filename}.java</h2><span class="file-meta">${line_count} lines | ${file_size} bytes</span></div>
    <pre><code>${escaped}</code></pre>
</div>
FILEBLOCK
    done

    # Close document
    cat >> "$output" << FOOTER
</div>
<footer>Auto-generated by KnightLight Documentation Pipeline</footer>
<script>
document.querySelectorAll('nav a').forEach(function(a){
    a.addEventListener('click',function(e){
        e.preventDefault();
        var t=document.querySelector(this.getAttribute('href'));
        window.scrollTo({top:t.offsetTop-85,behavior:'smooth'});
    });
});
</script>
</body>
</html>
FOOTER

    chmod 644 "$output"
    echo "[OK] Created combined view: ALL_SOURCE.html ($total_files files, $total_lines lines)" | tee -a "$LOG_FILE"
}

# =====================================================================
# MAIN EXECUTION
# =====================================================================

{
    echo "=========================================================================="
    echo "Conversion Session: $(date '+%Y-%m-%d %H:%M:%S')"
    echo "Script Version: 4.0 (LEAN - Combined view only)"
    echo "Java Source: $(cd "$JAVA_SRC_DIR" && pwd)"
    echo "Output Directory: $(cd "$DOCS_DIR" && pwd)"
    echo "Java Files Found: $(find "$JAVA_SRC_DIR" -maxdepth 1 -name "*.java" -type f | wc -l)"
    echo "=========================================================================="
} >> "$LOG_FILE"

echo "=========================================================================="
echo "  Java-to-HTML Converter v4.0 (LEAN)"
echo "  Output: $(cd "$DOCS_DIR" && pwd)"
echo "=========================================================================="
echo ""

# Generate combined single-page view ONLY
generate_combined_page

echo ""
echo "=========================================================================="
echo "  Conversion complete. Check .conversion-audit.log for details."
echo "=========================================================================="
echo ""
echo "Generated files:"
echo "  docs/ALL_SOURCE.html     - Combined single-page view (best for AI review)"
echo ""
echo "------------------------------------------------------------"
echo "Deploy to GitHub (copy paste this single line):"
echo ""
echo "git add docs/ && git commit -m \"Add HTML documentation for all classes\" && git push origin feature/integrate-new-systems"
echo ""
echo "------------------------------------------------------------"
echo "NOTE: Do NOT auto-push from this script."
echo "      Review changes manually before deploying."
echo "============================================================"
