#!/bin/bash
# generate-all-source.sh - Creates single-page combined source view
set -euo pipefail

DOCS_DIR="./docs"
JAVA_SRC_DIR="src/main/java/com/knightlight/game"
OUTPUT="$DOCS_DIR/ALL_SOURCE.html"

mkdir -p "$DOCS_DIR"

echo "[INFO] Generating combined source view..."

# Start building file list
total_files=0
total_lines=0

# First pass: count files and lines, build nav HTML
nav_html=""
for java_file in "$JAVA_SRC_DIR"/*.java; do
    filename=$(basename "$java_file" .java)
    class_id=$(echo "${filename,,}" | tr -cd '[:alnum:]')
    line_count=$(wc -l < "$java_file")
    total_files=$((total_files + 1))
    total_lines=$((total_lines + line_count))
    nav_html="${nav_html}<a href=\"#${class_id}\">${filename}</a> "
done

# Write header with nav already inlined
cat > "$OUTPUT" << HEADER
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>KnightLight - All Source</title>
<style>
body { font-family: monospace; background: #1a1a2e; color: #eaeaea; margin: 0; }
header { background: #6d4aff; padding: 20px; position: sticky; top: 0; z-index: 100; }
header h1 { color: white; margin: 0; }
.stats { color: #ccc; font-size: 0.85em; margin-top: 5px; }
nav { background: #2a2a4a; padding: 12px; position: sticky; top: 65px; z-index: 99; overflow-x: auto; white-space: nowrap; }
nav a { color: #aaaaff; text-decoration: none; margin-right: 15px; padding: 4px 8px; border-radius: 4px; }
nav a:hover { background: #4a4a8a; }
.file { border: 1px solid #4a4a8a; margin: 20px; background: #1e1e3e; border-radius: 8px; overflow: hidden; }
.file-header { background: #2a2a5a; padding: 12px 18px; border-bottom: 2px solid #6d4aff; display: flex; justify-content: space-between; align-items: center; }
.file-header h2 { color: #d0d0ff; font-size: 1.2em; margin: 0; }
.file-meta { color: #888; font-size: 0.8em; }
pre { padding: 18px; overflow-x: auto; background: #0f0f1e; margin: 0; white-space: pre; }
code { font-family: "Courier New", monospace; color: #d0d0ff; font-size: 0.9em; }
footer { padding: 25px; color: #666; text-align: center; border-top: 1px solid #4a4a8a; }
</style>
</head>
<body>
<header>
<h1>KnightLight - Complete Source Code</h1>
<div class="stats">${total_files} files | ${total_lines} lines | $(date '+%Y-%m-%d %H:%M')</div>
</header>
<nav>${nav_html}</nav>
<div id="files">
HEADER

# Second pass: write each file section
for java_file in "$JAVA_SRC_DIR"/*.java; do
    filename=$(basename "$java_file" .java)
    class_id=$(echo "${filename,,}" | tr -cd '[:alnum:]')
    line_count=$(wc -l < "$java_file")
    file_size=$(wc -c < "$java_file")

    escaped=$(sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g' "$java_file")

    cat >> "$OUTPUT" << FILEBLOCK

<div class="file" id="${class_id}">
    <div class="file-header"><h2>${filename}.java</h2><span class="file-meta">${line_count} lines | ${file_size} bytes</span></div>
    <pre><code>${escaped}</code></pre>
</div>
FILEBLOCK
done

# Close document
cat >> "$OUTPUT" << FOOTER
</div>
<footer>Auto-generated by KnightLight Documentation Pipeline</footer>
<script>
document.querySelectorAll('nav a').forEach(function(a){
    a.addEventListener('click',function(e){
        e.preventDefault();
        var t=document.querySelector(this.getAttribute('href'));
        window.scrollTo({top:t.offsetTop-85,behavior:'smooth'});
    });
});
</script>
</body>
</html>
FOOTER

echo "[OK] Created: $OUTPUT ($total_files files, $total_lines lines)"
